<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Paga tu cuenta aqu_cuentanumero</name>
   <tag></tag>
   <elementGuidId>624690e3-42e1-4a64-98de-5cc39a1b0208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cuenta_numero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cuenta_numero</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8300be51-608e-42db-b8ad-c81d7913f0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control string required</value>
      <webElementGuid>f16e07bd-cb90-4b35-ac63-82a64e4f864d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-trigger</name>
      <type>Main</type>
      <value>input focusin focusout</value>
      <webElementGuid>fc39175b-7eb6-4240-94b8-b906addc446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>a06fdb82-a5dd-4ff6-aec5-65e8fd6c6866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d4624b6c-2cf0-4c64-910d-da262e692e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f310ddc-7193-49e5-85e8-bde04c7e3572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej. e24a65</value>
      <webElementGuid>28e9f2d4-6ae3-4f33-824e-7344651b662e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cae4ede8-63af-4126-876d-bdc0b4c06ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cuenta[numero]</value>
      <webElementGuid>ca248cf5-d82e-4aad-ab26-0d8bb891bb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cuenta_numero</value>
      <webElementGuid>f230a39a-2727-4e75-b9b7-5aa784d5454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-lg&quot;]/div[@class=&quot;inner-body&quot;]/div[@class=&quot;row row-sm&quot;]/div[@class=&quot;col-lg-5 col-md-12&quot;]/div[@class=&quot;d-none d-sm-none d-md-block&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;simple_form form-horizontal&quot;]/div[@class=&quot;form-group mg-b-0&quot;]/div[@class=&quot;form-group string required cuenta_numero&quot;]/input[@id=&quot;cuenta_numero&quot;]</value>
      <webElementGuid>b4987d56-5e93-435d-8198-297ffba0d38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cuenta_numero']</value>
      <webElementGuid>0cf26ab4-c6f9-4a02-843f-0cf0fca9b0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>888607b8-c6cb-463e-b2d9-7502618df3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Ej. e24a65' and @type = 'text' and @name = 'cuenta[numero]' and @id = 'cuenta_numero']</value>
      <webElementGuid>a8597a05-c685-424b-a782-c5a229647dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
