<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Paga tu cuenta aqu_commit</name>
   <tag></tag>
   <elementGuidId>f7c367ff-af19-4e99-9aeb-1bf34bc8d86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='commit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;commit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>038bfe12-e666-4da3-9a69-65282a3f3e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f08bc5ca-c7e9-4745-adc6-062650a4dacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>96211371-041c-4cc2-aefb-91c890801a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>b8501b4d-c3e5-4f29-babe-c612d861d6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn ripple btn-success btn-lg btn-rounded boton-ancho btn-continuar-edipay</value>
      <webElementGuid>b92af6e9-650e-42b0-85db-f8f2599b1445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Espere...</value>
      <webElementGuid>aaa06f22-5275-4a17-9ec6-6e4eac7810d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>9f44f5ee-2fa2-42d6-b4f8-b4123744b7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-lg&quot;]/div[@class=&quot;inner-body&quot;]/div[@class=&quot;row row-sm&quot;]/div[@class=&quot;col-lg-5 col-md-12&quot;]/div[@class=&quot;d-none d-sm-none d-md-block&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;simple_form form-horizontal&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-9 d-none d-sm-none d-md-block&quot;]/input[@class=&quot;btn btn ripple btn-success btn-lg btn-rounded boton-ancho btn-continuar-edipay&quot;]</value>
      <webElementGuid>f79a9223-fb4a-467e-9236-54df52774a78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='commit']</value>
      <webElementGuid>7c38c164-f672-45ee-a580-2f8ef8f19269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0c98ba07-3e34-4e36-a9d5-c1bbb08962d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit']</value>
      <webElementGuid>e73434a6-a449-4cf6-b2da-227426b3c64c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
